on: push
name: ğŸš€ Deploy:NodeJS
jobs:
  web-deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: ğŸ‰ Deploy to https://dexa.jefriherditriyanto.com/
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: âœ… Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: ğŸ•“ Delayed 10 Second
        run: |
          sleep 10

      - name: ğŸŒŠ Install Dependencies
        run: |
          npm install

      - name: âš’ï¸ Build
        run: |
          npm run build

      - name: ğŸš« Remove Meta Files & Folders
        run: |
          rm -rf .github
          rm -rf node_modules
          rm -rf src
          rm .gitignore
          rm dexa-training.postman_collection.json
          rm nodemon.json
          rm package-lock.json || true
          rm package.json
          rm README.md
          rm soal_test.js
          rm yarn.lock || true

      - name: ğŸ“ Top Level Change
        run: |
          mv -v ./dist/* ./
          rm -rf dist

      - name: ğŸ”£ Rename index.js to app.js
        run: |
          mv index.js app.js

      - name: ğŸ’¯ Configuration for Production
        run: |
          sed -i 's/DB_SYNC=true/DB_SYNC=false/g' .env
          sed -i 's/database_host/localhost/g' .env
          sed -i 's/database_username/${{secrets.db_user}}/g' .env
          sed -i 's/database_password/${{secrets.db_pass}}/g' .env
          sed -i 's/database_name/${{secrets.db_name}}/g' .env

      - name: ğŸ’¾ Sync files to Server ğŸ“¡
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.partnerku.online
          username: ${{secrets.ftp_email}}
          password: ${{secrets.ftp_password}}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
